/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/src/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/ForgotPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/GameScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/LeaderboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/MainMenu`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/store/authSlice`; params?: Router.UnknownInputParams; } | { pathname: `/src/store`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/src/navigation/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/ForgotPasswordScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/GameScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/LeaderboardScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/MainMenu`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/RegisterScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/store/authSlice`; params?: Router.UnknownOutputParams; } | { pathname: `/src/store`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/src/navigation/AppNavigator${`?${string}` | `#${string}` | ''}` | `/src/screens/ForgotPasswordScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/GameScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/LeaderboardScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/LoginScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/MainMenu${`?${string}` | `#${string}` | ''}` | `/src/screens/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/src/screens/RegisterScreen${`?${string}` | `#${string}` | ''}` | `/src/store/authSlice${`?${string}` | `#${string}` | ''}` | `/src/store${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/src/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/ForgotPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/GameScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/LeaderboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/MainMenu`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/store/authSlice`; params?: Router.UnknownInputParams; } | { pathname: `/src/store`; params?: Router.UnknownInputParams; };
    }
  }
}
